### ISSUE TITLE
Could you stop using "rank~" alias in assemble_query method?

### ISSUE THREAD

**Issue by naoa** [textacular/textacular#87]
Currently, `def assemble_query` is using alias rank name by `AS`.

https://github.com/textacular/textacular/blob/f39bf8c99074039f8844b0c8e39d457aa95f93f5/lib/textacular.rb#L126

Also ActiveRecord change query to alias name using such as "AS alias_0" if use `include` method for eagar loading.

``` rb
Post.includes(:comments).search(body: "hoge")
```

``` sql
SELECT  DISTINCT "posts"."id", "posts"."rank67198880134037959" AS alias_0 FROM "posts" LEFT OUTER JOIN ...
```

This query causes syntax error because "rank~" column doesn't exist to overwrite query by ActiveRecord if use eagar loading.

Could you please stop using "rank" alias?

For example, the following code is passed even if use eager loading.

``` rb
def assemble_query(similarities, conditions, exclusive)
    select("#{quoted_table_name + '.*,' if select_values.empty?} #{similarities.join(" + ")}").
      where(conditions.join(exclusive ? " AND " : " OR ")).
      order("#{similarities.join(" + ")} DESC")
end
```

**Comment by joemsak** [comment]
Confirmed same problem in production, suggested patch works

**Comment by jcholder-legal** [comment]
Also experiencing the same problem. @joemsak: Thanks for the patch in the meantime!

**Comment by gregmolnar** [comment]
@jcholder-legal What version of activerecord do you have this issue with?

**Comment by gregmolnar** [comment]
I probably misunderstand something because I can't reproduce the problem. There is even a spec to make sure `includes` is working with textacular: https://github.com/textacular/textacular/blob/master/spec/textacular/searchable_spec.rb#L187
Would one of you mind to create a failing test based on this report template? https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb
